title: "GamemakerChina 文库"
description: "收录已经过翻译的 GM 文章"
url: 
baseurl: "/"
author: "GamemakerChina 文库"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
  - CHANGELOG.md